CREATE TYPE user_role AS ENUM ('SELLER','SUPPLIER','HYBRID','DEVELOPER','ADMIN');
CREATE TYPE onboarding_step AS ENUM (
  'ROLE_SELECTION',   -- just registered, email verified, no role chosen yet
  'PLAN_SELECTION',   -- SELLER role chosen, must pick a subscription plan
  'BUSINESS_SETUP',   -- plan chosen (SELLER) or SUPPLIER role chosen — filling in profile
  'COMPLETE'          -- all required onboarding steps done
);
CREATE TYPE business_status AS ENUM ('INCOMPLETE','PENDING_VERIFICATION','ACTIVE','SUSPENDED');
CREATE TYPE business_sector AS ENUM (
  'FASHION_APPAREL','ELECTRONICS','FOOD_BEVERAGE','HEALTH_BEAUTY',
  'HOME_LIVING','BOOKS_STATIONERY','SPORTS_FITNESS','TOYS_GAMES',
  'AUTOMOTIVE','JEWELRY_ACCESSORIES','ART_CRAFTS','DIGITAL_PRODUCTS',
  'SERVICES','GENERAL_MERCHANDISE','OTHER'
);
CREATE TYPE address_type AS ENUM ('PERSONAL','BUSINESS');
CREATE TYPE document_type AS ENUM ('NATIONAL_ID','PASSPORT','DRIVERS_LICENSE','UTILITY_BILL','BUSINESS_REGISTRATION','OTHER');
CREATE TYPE document_status AS ENUM ('PENDING','APPROVED','REJECTED');
CREATE TYPE domain_type AS ENUM ('SUBDOMAIN','CUSTOM');
CREATE TYPE domain_status AS ENUM ('PENDING','ACTIVE','FAILED','SUSPENDED');
CREATE TYPE staff_status AS ENUM ('INVITED','ACTIVE','SUSPENDED','REMOVED');
CREATE TYPE subscription_status AS ENUM ('TRIAL','ACTIVE','PAST_DUE','CANCELLED','EXPIRED');
CREATE TYPE plan_tier AS ENUM ('STARTER','PRO','GROWTH');
CREATE TYPE product_status AS ENUM ('DRAFT','ACTIVE','ARCHIVED');
CREATE TYPE supplier_product_status AS ENUM ('DRAFT','PENDING_REVIEW','ACTIVE','PAUSED','REJECTED');
CREATE TYPE order_type AS ENUM ('DIRECT','DROPSHIP_INAPP','DROPSHIP_EXTERNAL');
CREATE TYPE order_status AS ENUM ('PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','REFUNDED');
CREATE TYPE payment_status AS ENUM ('PENDING','PAID','FAILED','REFUNDED','PARTIALLY_REFUNDED');
CREATE TYPE dropship_order_status AS ENUM (
  'PENDING','CONFIRMED','PROCESSING','SHIPPED',
  'AWAITING_SELLER_CONFIRMATION','DELIVERED','CANCELLED','DISPUTED'
);
CREATE TYPE seller_confirmation_status AS ENUM ('NOT_REQUIRED','PENDING','CONFIRMED','DISPUTED');
CREATE TYPE escrow_status AS ENUM ('HELD','AWAITING_SELLER_CONFIRMATION','RELEASED','REFUNDED','DISPUTED');
CREATE TYPE revenue_recipient AS ENUM ('SUPPLIER','SELLER','DEVELOPER','PLATFORM');
CREATE TYPE payment_gateway AS ENUM ('VARANDA_PAY','FLUTTERWAVE_CUSTOM','STRIPE_CUSTOM');
CREATE TYPE payment_provider AS ENUM ('PAYSTACK','STRIPE','FLUTTERWAVE','MANUAL');
CREATE TYPE stock_movement_type AS ENUM ('SALE','RETURN','MANUAL_INCREASE','MANUAL_DECREASE','IMPORT','BUNDLE_SALE','VARIANT_CREATION');
CREATE TYPE third_party_provider AS ENUM ('PRINTFUL','ALIEXPRESS','ZENDROP','CUSTOM');
CREATE TYPE campaign_channel AS ENUM ('EMAIL','SMS');
CREATE TYPE campaign_status AS ENUM ('DRAFT','SCHEDULED','SENDING','SENT','FAILED');
CREATE TYPE discount_type AS ENUM ('PERCENTAGE','FIXED_AMOUNT','FREE_SHIPPING');
CREATE TYPE page_type AS ENUM ('HOME','PRODUCTS','PRODUCT_DETAIL','CATEGORY','CART','CHECKOUT','ABOUT','CONTACT','POLICY','CUSTOM');
CREATE TYPE developer_status AS ENUM ('PENDING','ACTIVE','SUSPENDED');

-- Note: businesses.owner_id FK is defined as ON DELETE CASCADE in 006_create_businesses.sql
-- so deleting a user automatically removes their business and all cascading data.
